swagger: '2.0'

info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'

host: localhost:3001
basePath: /api/v1
schemes:
  - http

paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type : string
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error


  /transactions/{idUser}/{idAccount}:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transaction API
      description: API to get the list of transactions for a specific account and a specific user
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          type: string
          name: idUser
          description: The user id
          required: true
        - in: path
          type: string
          name: idAccount
          description: The account id
          required: true
        - in: query
          type: string
          name: month
          description: selected month
          required: false
      produces:
        - application/json
      responses:
        "200":
          description: Transaction retrieved successfully
          schema:
            $ref: "#/definitions/TransactionsResponse"
        "400":
          description: Invalid Fields
        '404':
          description: Invalid idUser or idAccount
        "500":
          description: Internal Server Error

          
  /transactions/{idUser}/{idAccount}/{idTransaction}:
    get: 
      security: 
        - Bearer: []
      tags: 
        - Transactions Module
      summary: Get transactions for the current month
      description: Retrieve user transactions grouped by account
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          type: string
          name: idUser
          description: The user id
          required: true
        - in: path
          type: string
          name: idAccount
          description: The account id
          required: true
        - in: path
          type: string
          name: idTransaction
          description: The transaction id
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema: 
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid Fields
        '404':
          description: Invalid idUser or idAccount or idTransaction
        '500':
          description: Internal Server Error

    patch:
      security: 
        - Bearer: []
      tags:
        - Transactions Module
      summary: Partially update a transaction (add, modify or remove fields)
      description: Add news fields, ypdate existing fields or remove fields from a transaction
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
          type: string
        - in: path
          type: string
          name: idUser
          description: The user id
          required: true
        - in: path
          type: string
          name: idAccount
          description: The account id
          required: true
        - in: path
          type: string
          name: idTransaction
          description: The transaction id
          required: true
        - in: body
          name: body
          description: Transaction's note Payload
          schema:
            $ref: '#/definitions/ModificationTransaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/Transaction'
        '400':
          description: Invalid request
        '401':
          description: Invalid token
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error


securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header


definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name

  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password

  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string

  LoginResponse:
    type: object
    properties:
      token:
        type: string

  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  TransactionsResponse:
    type: object
    properties: 
      status:
        type: integer
      message:
        type: string
      body: 
        type: object
        properties:
          transactions:
            type: array
            description: Array Of transactions
            items:
              $ref: "#/definitions/Transaction"

  Transaction:
    type: object
    properties:
      id:
        type: string
      idUser:
        type: string
      date:
        type: string
        pattern: "yyyy-mm-dd"
      amount:
        type: number
      balance:
        type: number
      description:
        type: string
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string

  ModificationTransaction:
    type: objet
    properties:
      category:
        type: string
      notes:
        type: string 
